name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test-code-style:
    name: Code style tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        run: >-
          python -m
          pip install
          poetry
          --user
      - name: Install dependencies
        run: |
          poetry install
      - name: Run flake8
        run: poetry run flake8 --config .flake8 --extend-ignore=D,E203 --verbose --statistics
      - name: Run isort
        run: poetry run isort . --check --verbose --diff --color
      - name: Run black
        run: poetry run black . --check --verbose --diff --color --fast
      - name: Run tests
        run: poetry run coverage run -m pytest --verbose
      - name: Upload coverage
        run: poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: run-${{ github.sha }}
